# Generated by Django 5.2.3 on 2025-06-30 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.IntegerField(max_length=20),
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('finger_id', models.IntegerField(max_length=20)),
                ('phone', models.IntegerField(max_length=20)),
                ('date_of_birth', models.DateField(max_length=20)),
                ('diabetes_type', models.CharField(choices=[('Type 1', 'Type 1'), ('Type 2', 'Type 2'), ('Gestational', 'Gestational')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
