# Generated by Django 5.2.3 on 2025-06-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_customuser_options_alter_customuser_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'all User', 'verbose_name_plural': 'all Users'},
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='finger_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
