# Generated by Django 5.2.3 on 2025-07-01 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_medicalstaffprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='homepage.medicalstaffprofile'),
        ),
    ]
