# Generated by Django 5.2.3 on 2025-07-01 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_patientprofile_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='homepage.medicalstaffprofile'),
        ),
    ]
