# Generated by Django 5.2.3 on 2025-07-03 18:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_alter_patientprofile_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalstaffprofile',
            name='last_dashboard_check',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
