# Generated by Django 5.2.3 on 2025-07-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_medicalstaffprofile_last_dashboard_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='date_of_birth',
            field=models.DateField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='finger_id',
            field=models.IntegerField(null=True),
        ),
    ]
