# Generated by Django 5.2.3 on 2025-07-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_alter_patientprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
