# Generated by Django 5.2.3 on 2025-07-03 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_alter_patientprofile_doctor'),
        ('medical_staff_blogs', '0002_remove_blogpost_image_url_blogpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.medicalstaffprofile'),
        ),
    ]
