# Generated by Django 5.2.3 on 2025-07-01 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homepage', '0005_medicalstaffprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_sugar', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('reading_type', models.CharField(choices=[('Fasting', 'Fasting'), ('Random', 'Random'), ('After Meal', 'After Meal')], max_length=50)),
                ('note', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.patientprofile')),
            ],
        ),
    ]
