# Generated by Django 5.2.3 on 2025-07-01 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_medicalstaffprofile'),
        ('patient_blood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addentry',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.patientprofile'),
        ),
    ]
