# Generated by Django 5.2.3 on 2025-07-01 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_blood', '0003_alter_addentry_patient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addentry',
            options={'verbose_name': 'all Entry', 'verbose_name_plural': 'all Entry'},
        ),
    ]
